/*
 * mya_rcc.h
 *
 *  Created on: May 10, 2020
 *      Author: muyustan
 */

#ifndef MYA_RCC_H_
#define MYA_RCC_H_

#include "mya_stm32f407vg.h"


#define RCC_GPIOA_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN)
#define RCC_GPIOB_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN)
#define RCC_GPIOC_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN)
#define RCC_GPIOD_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN)
#define RCC_GPIOE_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN)
#define RCC_GPIOF_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN) 
#define RCC_GPIOG_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN)
#define RCC_GPIOH_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN)
#define RCC_GPIOI_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOIEN)
#define RCC_GPIOJ_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOJEN)
#define RCC_GPIOK_EN() (RCC->AHB1ENR |= RCC_AHB1ENR_GPIOKEN)

#define RCC_SYSCFG_EN()     (RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN)
#define RCC_SYSCFG_DIS()    (RCC->APB2ENR &= ~(RCC_APB2ENR_SYSCFGEN))

#define RCC_TIM2_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM2EN)
#define RCC_TIM3_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM3EN)
#define RCC_TIM4_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM4EN)
#define RCC_TIM5_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM5EN)
#define RCC_TIM6_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM6EN)
#define RCC_TIM7_EN()   (RCC->APB1ENR |= RCC_APB1ENR_TIM7EN)
#define RCC_TIM12_EN()  (RCC->APB1ENR |= RCC_APB1ENR_TIM12EN)
#define RCC_TIM13_EN()  (RCC->APB1ENR |= RCC_APB1ENR_TIM13EN)
#define RCC_TIM14_EN()  (RCC->APB1ENR |= RCC_APB1ENR_TIM14EN)

void mya_rcc_clock_config(void);

#endif /* MYA_RCC_H_ */
